### PR TITLE
cmake: Use GNUInstallDirs for installtion

### PR DESCRIPTION
**Pull request by cryptomilk**
Use the GNUInstallDirs module provided by cmake. This will allow distributions to install it correctly.

### CODE REVIEW

**Comment by kentrussell** [comment]
Hi @cryptomilk , I was wondering about this portion of your patch:
    COMMAND rm -rf *.deb *.rpm *.tar.gz
    COMMAND make package


Is that required for GnuInstallDirs' installation?

**Comment by cryptomilk** [comment]
No it isn't needed, I guess I removed it by accident.

**Comment by kentrussell** [comment]
This has been pulled internally, but it missed the 2.3 cutoff. I'm working to get it into 2.4

**Comment by kentrussell** [comment]
This will be in 2.5

**Comment by kentrussell** [comment]
Integrated into 2.5

**Pull request closed without merging**
