### PR TITLE
Install header files and pkg-config files

### PR DESCRIPTION
**Pull request by cryptomilk**
This correctly installs the header and pkg-config files correctly in the system so that others can link against the library.

### CODE REVIEW

**Comment by kentrussell** [comment]
Sorry @cryptomilk for the delay (I integrated it, but now I am looking at it objectively). I was wondering about this patch specifically. We install the pkg-config and headers in the hsakmt-dev package, is there a reason why it needs to move to the regular hsakmt package instead?

**Comment by kentrussell** [comment]
This patch will end up being changed. We already include the headers/pkgconfig in the -dev package, but that's not installed when a make install is done. I'm going to add "make install-dev" to the regular list so that it installs the packages as expected.

**Comment by cryptomilk** [comment]
I'm sorry, but *none* of the open source project install header files in a separate `make install` command.

**Comment by cryptomilk** [comment]
The RPM spec file or dpkg dsc file put them in a seperate devel package when being packaged:

Feel free to check https://src.fedoraproject.org/browse/projects/

**Comment by kentrussell** [comment]
This has been pulled internally, but it missed the 2.3 cutoff. I'm working to get it into 2.4

**Comment by kentrussell** [comment]
This will be in 2.5

**Comment by kentrussell** [comment]
Integrated into 2.5

**Pull request closed without merging**
