### PR TITLE
Separate build version from library version

### PR DESCRIPTION
**Pull request by tstellar**
This patch separates the build version (i.e. ROCm version) from the
library version used to set the SONAME of the shared objects.  This
prevents the SONAME from getting bumped each time there is a new ROCm
release without any change to the libhsakmt ABI.

1.0.6 was choosen as the library version since this was the
last library version used prior to switching to the ROCm version
numbers.

### CODE REVIEW

**Comment by cryptomilk** [comment]
The best would be to also use https://github.com/ansasaki/abimap

**Comment by tstellar** [comment]
Could that be done as a follow-up change?

**Comment by kentrussell** [comment]
This has been pulled internally, but it missed the 2.3 cutoff. I'm working to get it into 2.4

**Comment by kentrussell** [comment]
This will be in 2.5

**Comment by kentrussell** [comment]
Integrated into 2.5

**Pull request closed without merging**
