### PR TITLE
Add extended coherence memory flag

### PR DESCRIPTION
**Pull request by dayatsin-amd**
Add support for new flag for memory allocation that will provide system-scope coherent atomics

<Note: I will bring-in this change internal AMD repository. Posting patch here for reference only>

### CODE REVIEW

**Comment by fdavid-amd** [comment]
All other flags are adjectives, not nouns. Could this be EXT_COHERENT instead of EXT_COHERENCE?

**Comment by fxkamd** [comment]
We talked about explicitly failing for invalid combinations of flags (e.g. CoarseGrain | ExtCoherence). I don't see that in this patch.

**Comment by dayatsin-amd** [comment]
I have 2 changes pending, but having connection problems with dev-machine so cannot upload. Please wait before reviewing again.

**Comment by dayatsin-amd** [comment]
> I have 2 changes pending, but having connection problems with dev-machine so cannot upload. Please wait before reviewing again.

I am done. Uploaded latest changes

**Pull request closed without merging**
