### PR TITLE
hsakmt-dev should not install linux kernel headers

### PR DESCRIPTION
**Pull request by candrews**
hsakmt-dev should not install include/linux/* (currently just kfd_ioctl.h) as those are linux kernel headers provided by the linux kernel header packages (`linux-headers-*` on Debian/Ubuntu or `kernel-headers-*` on Red Hat / Fedora)

### CODE REVIEW

**Comment by fxkamd** [comment]
I'll apply this one, not PR#41. We do need kfd_ioctl.h for building libhsakmt. Depending on the latest kernel headers to build our library is something we're trying to avoid. But you're right, we don't need to install this header file as the clients of libhsakmt don't need it.

**Comment by fxkamd** [comment]
Can I add a Signed-off-by: Craig Andrews <...> to your commits as certificate of origin? See also https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for.

**Comment by candrews** [comment]
> Can I add a Signed-off-by: Craig Andrews <...> to your commits as certificate of origin?

You absolutely can. If necessary, I can update any PRs/commits myself doing so, just let me know what's better/easier for you.

**Comment by fxkamd** [comment]
I'll do it on my local branch, where I'm cherry-picking your patches and running them through our internal build/test and code review process. Thanks!

**Comment by candrews** [comment]
@fxkamd Do you have any news? I'm eager to get this merged and stop having to carry/maintain the patch :)

**Comment by kentrussell** [comment]
We missed the branching for 2.8, but it's slated to be included in 2.9.

**Comment by candrews** [comment]
https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/commit/21f4754ceb192a86da207affd9e69ab847d81b26

**Pull request closed without merging**
