### PR TITLE
use pkg-config to link with libpci

### PR DESCRIPTION
**Pull request by jvesely**

### CODE REVIEW

**Comment by jvesely** [comment]
ping. @jedwards-AMD, you seem to be handling cmake for this project, any comments?

**Comment by jvesely** [comment]
ping

**Comment by jvesely** [comment]
ping

**Comment by folklore1984** [comment]
I sent a pull request to attempt to fix up all this stuff,
https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/pull/13

**Comment by fxkamd** [comment]
Thanks. I've applied the patches to out internal tree. They will be included in the next big release.

**Pull request closed without merging**
