### PR TITLE
Fix GPU cache size unit from KiB to B

### PR DESCRIPTION
**Pull request by kazuki**

### CODE REVIEW

**Comment by fxkamd** [comment]
I'm checking with the owner of the Thunk specification what unit we should be reporting.

**Comment by kazuki** [comment]
Thanks.

Currently, ROCR's hsa_cache_get_info(HSA_CACHE_INFO_SIZE) returns size in byte unit in cpu agent but returns size in KiB unit in gpu agent.

Maybe, ROCT interface returns size in KiB unit.
And to fix above problem, fix ROCT/ROCR, to ROCT returns cpu cache size in KiB unit and ROCR returns cpu/gpu cache size in byte unit.

**Comment by kentrussell** [comment]
@fxkamd Did we ever get a response on this?

**Comment by kentrussell** [comment]
This was resolved in ROCr in ROCm 4.3 (502dc3a9c99dc Get GPU cache information from KFD)

**Pull request closed without merging**
